##############################################################
# DO NOT FORGET TO SET THE ENVIRONMENT VARIABLES IN THE FILE
#            .env
# which is automatically sourced when the container are started

# we are using Compose file format version 3
version: '3'

# we want to start the following 
services:
   mariadb:
     image: mariadb               # use mariadb image
     ports:
       - '3306:3306'              # map port 3306 of host 
                                  # to 3306 of container
     volumes:
       - ./db-data:/var/lib/mysql # mount host directory '/db-data' 
                                  # on '/var/lib/mysql' of container
                                  # to make db persistant 
     restart: always              # always restart the services
                                  # when it stops
     environment:                 # make environment variables 
                                  # available in container
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
